export const contentConstants = {
    CONTENT_LOAD_REQUEST: "CONTENT_LOAD_REQUEST",
    CONTENT_ID_REQUEST: "CONTENT_ID_REQUEST",
    CONTENT_LOAD_SUCCESS: "CONTENT_LOAD_SUCCESS",
    CONTENT_ID_SUCCESS: "CONTENT_ID_SUCCESS",

    PAGE_SIZE: 30,
    CONTENT_LIMIT: 100
};